# Generated by Django 3.0.7 on 2020-06-26 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Год публикации')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookpublishing_book', to='p_library.Book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название издательства')),
                ('books', models.ManyToManyField(through='p_library.BookPublishing', to='p_library.Book', verbose_name='Книги')),
            ],
        ),
        migrations.AddField(
            model_name='bookpublishing',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookpublishing_publisher', to='p_library.Publisher', verbose_name='Издательство'),
        ),
    ]
